package ru.practicum.locations.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import ru.practicum.locations.dto.LocationDto;
import ru.practicum.locations.model.Location;

import javax.annotation.processing.Generated;

@Mapper(componentModel = "spring")
@Generated("AutoGeneratedByMapStruct")
public interface LocationMapper {

    LocationMapper INSTANCE = Mappers.getMapper(LocationMapper.class);

    Location locationDtoToLocation(LocationDto locationDto);
}
