version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-server:
    build: ./main-service
    image: main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - STATS_CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm_main
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

