package ru.practicum.compilations.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import ru.practicum.compilations.dto.CompilationDto;
import ru.practicum.compilations.model.Compilation;

import javax.annotation.processing.Generated;
import java.util.List;

@Mapper(componentModel = "spring")
@Generated("AutoGeneratedByMapStruct")
public interface CompilationMapper {
    CompilationMapper NSTANCE = Mappers.getMapper(CompilationMapper.class);

    CompilationDto compilatonsToCompilationsDto(Compilation compilation);
    List<CompilationDto> compilatonsToCompilationsDto(List<Compilation> compilation);


}
