package ru.practicum.categories.mapper;

import java.util.List;
import javax.annotation.processing.Generated;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import ru.practicum.categories.dto.CategoryDto;
import ru.practicum.categories.model.Category;

@Mapper(componentModel = "spring")
@Generated("AutoGeneratedByMapStruct")
public interface CategoriesMapper {
    CategoriesMapper NSTANCE = Mappers.getMapper(CategoriesMapper.class);

    CategoryDto categoriesToCategoriesDto(Category category);

    List<CategoryDto> categoriesToCategoriesDto(List<Category> categories);
}
