package ru.practicum.events.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;
import ru.practicum.events.dto.EventFullDto;
import ru.practicum.events.model.Event;

import javax.annotation.processing.Generated;


@Mapper(componentModel = "spring")
@Generated("AutoGeneratedByMapStruct")
public interface EventMapper {

    EventMapper NSTANCE = Mappers.getMapper(EventMapper.class);


    EventFullDto eventToEventFullDto(Event event, Long views);
}
